# Generated by Django 5.2.2 on 2025-06-09 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservas.espacio')),
            ],
            options={
                'unique_together': {('espacio', 'fecha', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
