# Generated by Django 5.2.2 on 2025-06-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='nombre',
            field=models.CharField(choices=[('Salón 201', 'Salón 201'), ('Salón 202', 'Salón 202'), ('Salón 203', 'Salón 203'), ('Salón 204', 'Salón 204'), ('Salón 205', 'Salón 205'), ('Salón 206', 'Salón 206')], max_length=20, unique=True),
        ),
    ]
