# Generated by Django 5.2.2 on 2025-06-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0002_alter_espacio_descripcion_alter_espacio_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='motivo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='necesidades',
            field=models.TextField(blank=True),
        ),
    ]
