# Generated by Django 5.2.2 on 2025-06-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0003_reserva_motivo_reserva_necesidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='nombre_completo',
            field=models.CharField(default='Nombre Pendiente', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nombre_usuario',
            field=models.EmailField(max_length=254),
        ),
    ]
