# Generated by Django 5.2.7 on 2025-11-02 00:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(default='Estudiante Demo', max_length=100)),
                ('sala', models.CharField(choices=[('SALA_1', 'Sala 1'), ('SALA_2', 'Sala 2'), ('SALA_3', 'Sala 3'), ('SALA_4', 'Sala 4'), ('SALA_5', 'Sala 5'), ('SALA_6', 'Sala 6'), ('SALA_7', 'Sala 7')], default='SALA_1', max_length=10)),
                ('hora_inicio', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
